FROM postgres:16-alpine

ENV USE_LLVM=0

RUN apk add --no-cache \
        git \
        build-base \
        clang19 \
        llvm19-dev \
    && git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && cd .. \
    && rm -rf pgvector \
    && apk del git build-base clang19 llvm19-dev