"""initial_migration

Revision ID: 0001
Revises: 
Create Date: 2026-04-13 16:06:36.892496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from ingestion_service.models import PGSparseVector
from ingestion_service.models import PGVector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('source_lang', sa.Text(), nullable=False),
    sa.Column('text_original', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('translation_failed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('bbox', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('dense_vec', PGVector(1024), nullable=True),
    sa.Column('sparse_vec', PGSparseVector(250002), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_chunks_block_type', 'chunks', ['block_type'], unique=False)
    op.create_index('ix_chunks_doc_id', 'chunks', ['doc_id'], unique=False)
    op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_source_lang', 'chunks', ['source_lang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_source_lang', table_name='chunks')
    op.drop_index('ix_chunks_document_id', table_name='chunks')
    op.drop_index('ix_chunks_doc_id', table_name='chunks')
    op.drop_index('ix_chunks_block_type', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
