"""remove metadata

Revision ID: 0002
Revises: 0001
Create Date: 2026-04-13 21:47:51.824564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chunks_dense_hnsw'), table_name='chunks', postgresql_ops={'dense_vec': 'vector_ip_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('chunks_sparse_hnsw'), table_name='chunks', postgresql_ops={'sparse_vec': 'sparsevec_ip_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('chunks', 'bbox')
    op.drop_column('chunks', 'section_title')
    op.drop_column('chunks', 'translation_failed')
    op.drop_column('chunks', 'context')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chunks', sa.Column('translation_failed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('section_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chunks', sa.Column('bbox', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.create_index(op.f('chunks_sparse_hnsw'), 'chunks', ['sparse_vec'], unique=False, postgresql_ops={'sparse_vec': 'sparsevec_ip_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('chunks_dense_hnsw'), 'chunks', ['dense_vec'], unique=False, postgresql_ops={'dense_vec': 'vector_ip_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
