"""Add Tenant and DocumentCompliance tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-04-14 21:54:13.548313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_compliance')
    op.drop_index(op.f('chunks_dense_hnsw'), table_name='chunks', postgresql_ops={'dense_vec': 'vector_ip_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('chunks_sparse_hnsw'), table_name='chunks', postgresql_ops={'sparse_vec': 'sparsevec_ip_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.execute("UPDATE tenants SET email = name || '@example.com'")
    op.alter_column('tenants', 'email', nullable=False)
    op.add_column('tenants', sa.Column('subscription_plan', sa.String(length=50), server_default=sa.text("'free'::character varying"), nullable=False))
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('tenants', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_tenants_email', 'tenants', ['email'], unique=False)
    op.create_index('ix_tenants_is_active', 'tenants', ['is_active'], unique=False)
    op.create_index('ix_tenants_name', 'tenants', ['name'], unique=False)
    op.create_unique_constraint(None, 'tenants', ['name'])
    op.create_unique_constraint(None, 'tenants', ['email'])
    op.drop_column('tenants', 'financial_attrs')
    op.drop_column('tenants', 'admin_attrs')
    op.drop_column('tenants', 'technical_attrs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('technical_attrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('admin_attrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('financial_attrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_index('ix_tenants_name', table_name='tenants')
    op.drop_index('ix_tenants_is_active', table_name='tenants')
    op.drop_index('ix_tenants_email', table_name='tenants')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'metadata')
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'subscription_plan')
    op.drop_column('tenants', 'email')
    op.create_index(op.f('chunks_sparse_hnsw'), 'chunks', ['sparse_vec'], unique=False, postgresql_ops={'sparse_vec': 'sparsevec_ip_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('chunks_dense_hnsw'), 'chunks', ['dense_vec'], unique=False, postgresql_ops={'dense_vec': 'vector_ip_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('document_compliance',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('extracted_criteria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('compliance_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_compliant', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('analyzed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_compliance_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('document_compliance_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_compliance_pkey')),
    sa.UniqueConstraint('document_id', name=op.f('document_compliance_document_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
