services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass yourpasswordhere

volumes:
  redis_data: